"""add phone to candidates and extend job_matches

Revision ID: cac74bdb8596
Revises: 
Create Date: 2026-03-25 21:28:24.117311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac74bdb8596'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('phone', sa.Text(), nullable=True))
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.add_column('job_matches', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('required_matches', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('job_matches', sa.Column('optional_matches', sa.ARRAY(sa.Text()), nullable=True))
    op.create_index(op.f('ix_job_matches_id'), 'job_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_matches_id'), table_name='job_matches')
    op.drop_column('job_matches', 'optional_matches')
    op.drop_column('job_matches', 'required_matches')
    op.drop_column('job_matches', 'job_description')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_column('candidates', 'phone')
    # ### end Alembic commands ###
